fix(pecl): better success message

diff --git a/lib/pecl b/lib/pecl
--- a/lib/pecl
+++ b/lib/pecl
@@ -243,8 +243,6 @@ function php::pecl::compile_extension() {
 
 
 function install_pecl_extension() {
-  local rc=1
-
   local extension_name="${1}"
   local version="${2}"
   local cache_dir="${3}"
@@ -309,8 +307,11 @@ function install_pecl_extension() {
 
   popd >/dev/null || return 1
 
-  php::pecl::enable_pecl_extension "${extension_name}"
-  rc="${?}"
-
-  return "${rc}"
+  if ! php::pecl::enable_pecl_extension "${extension_name}"; then
+    echo "Unable to activate PECL extension '${extension_name}' ${version_number}. Aborting." >&2
+    return 1
+  else
+    echo "Successfully installed PECL extension '${extension_name}' ${version_number}."
+    return 0
+  fi
 }
