fix(pecl): better error messages

diff --git a/lib/pecl b/lib/pecl
--- a/lib/pecl
+++ b/lib/pecl
@@ -264,7 +264,7 @@ function install_pecl_extension() {
   # If version is given as '*', try to retrieve the latest version number:
   if [[ "${version}" = '*' ]]; then
     if ! version_number="$( php::pecl::get_latest_version "${extension_name}" )"; then
-      echo "Unable retrieve PECL extension ${extension_name} latest version number. Aborting." >&2
+      echo "Unable to retrieve '${extension_name}' latest version number. Aborting." >&2
       return 1
     fi
   fi
@@ -272,32 +272,32 @@ function install_pecl_extension() {
 
   # Try to install extension from cache, but never fail:
   if php::pecl::install_from_cache "${extension_name}" "${version_number}" "${cache_dir}" "${ext_dir}"; then
-    echo "Successfully installed ${extension_name} ${version_number} from cache."
+    echo "Successfully installed '${extension_name}' ${version_number} from cache."
     return 0
   fi
 
 
   # The extension is not cached, we have to install it.
-  echo "Installing PECL extension ${extension_name} ${version_number}" | indent
+  echo "Installing PECL extension '${extension_name}' ${version_number}" | indent
 
   temp_dir="$( mktmpdir "pecl-extension" )"
   extension_temp_dir="${temp_dir}/${extension_name}-${version_number}"
 
   # Download:
   if ! archive="$( php::pecl::download_extension "${extension_name}" "${version_number}" "${temp_dir}" )"; then
-    echo "Unable to download PECL extension ${extension_name} ${version_number}. Aborting." >&2
+    echo "Unable to download PECL extension '${extension_name}' ${version_number}. Aborting." >&2
     return 1
   fi
 
   # Extract:
   if ! php::pecl::extract_extension "${archive}" "${extension_temp_dir}"; then
-    echo "Unable to unpack PECL extension ${extension_name}. Aborting." >&2
+    echo "Unable to unpack PECL extension '${extension_name}'. Aborting." >&2
     return 1
   fi
 
   # Compile:
   if ! php::pecl::compile_extension "${extension_temp_dir}" "${build_dir}" "${extension_name}"; then
-    echo "Unable to compile extension ${extension_name}. Aborting." >&2
+    echo "Unable to compile PECL extension '${extension_name}'. Aborting." >&2
     return 1
   fi
 
