chore(linting): fix linting

diff --git a/support/lib/php_ext b/support/lib/php_ext
--- a/support/lib/php_ext
+++ b/support/lib/php_ext
@@ -1,39 +1,44 @@
 #!/usr/bin/env bash
 
 function build_ext() {
-  local tempbuilddir=$1
-  local php_version=$2
-  local zend_api_version=$3
-  local ext_name=$4
+	local tempbuilddir="${1}"
+	local php_version="${2}"
+	local zend_api_version="${3}"
+	local ext_name="${4}"
 
-  # Only used for internal extensions
-  local php_src_dir=$5
+	# Only used for internal extensions
+	local php_src_dir="${5}"
 
-  echo "-----> Building extension $ext_name"
+	echo "-----> Building extension ${ext_name}"
 
-  local ext_dir="lib/php/extensions/no-debug-non-zts-${zend_api_version}"
-  mkdir -p "$tempbuilddir/$ext_dir" \
-    && mkdir -p "$tempbuilddir/etc/conf.d" \
-    && PREFIX="$tempbuilddir" EXT_DIR="$tempbuilddir/$ext_dir" ./build.sh "$php_version" "$zend_api_version" "$php_src_dir"; rc=$?
-  if [ $rc -ne 0 ] ; then
-    echo "Fail to build package"
-    exit 1
-  fi
+	local ext_dir="lib/php/extensions/no-debug-non-zts-${zend_api_version}"
+	mkdir --parents "${tempbuilddir}/${ext_dir}"
+	mkdir --parents "${tempbuilddir}/etc/conf.d"
+	#PREFIX="${tempbuilddir}" EXT_DIR="${tempbuilddir}/${ext_dir}" \
+	#	./build.sh "${php_version}" "${zend_api_version}" "${php_src_dir}"
+  	#rc="${?}"if [ $rc -ne 0 ] ; then
+
+	if ! PREFIX="${tempbuilddir}" EXT_DIR="${tempbuilddir}/${ext_dir}" \
+		./build.sh "${php_version}" "${zend_api_version}" "${php_src_dir}"
+	then
+		echo "Fail to build package"
+    	exit 1
+  	fi
 }
 
 function upload_ext() {
-  local tempbuilddir=$1
-  local tempdir=$2
-  local package_name=$3
-  local zend_api_version=$4
+	local tempbuilddir="${1}"
+	local tempdir="${2}"
+	local package_name="${3}"
+	local zend_api_version="${4}"
 
-  echo "-----> Uploading extension $ext_name"
+	echo "-----> Uploading extension ${ext_name}"
 
-  mkdir -p "package/ext/${zend_api_version}"
-  pushd "$tempbuilddir" > /dev/null
-  tar zcvf "$tempdir/package/ext/${zend_api_version}/php-${package_name}.tgz" .
-  popd
+	mkdir -p "package/ext/${zend_api_version}"
+	pushd "${tempbuilddir}" > /dev/null
+	tar zcvf "${tempdir}/package/ext/${zend_api_version}/php-${package_name}.tgz" .
+	popd
 
-  swift_upload "package/ext/${zend_api_version}/php-${package_name}.tgz"
-  "$basedir/package-checksum" "ext/${zend_api_version}/php-${package_name}"
+	swift_upload "package/ext/${zend_api_version}/php-${package_name}.tgz"
+	"${basedir}/package-checksum" "ext/${zend_api_version}/php-${package_name}"
 }
